FROM node:lts-alpine3.23 as frontend
WORKDIR /frontend
COPY ./  .
RUN npm install
RUN npm run build

FROM nginx
COPY --from=frontend /frontend/dist /usr/share/nginx/html
COPY --from=frontend /frontend/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]