export const conditionMap: Record<string, { label: string; color: string }> = {
  clear: { label: 'Céu limpo', color: 'bg-yellow-100 text-yellow-800' },
  mainly_clear: { label: 'Principalmente limpo', color: 'bg-yellow-100 text-yellow-800' },
  partly_cloudy: { label: 'Parcialmente nublado', color: 'bg-gray-100 text-gray-800' },
  overcast: { label: 'Nublado', color: 'bg-gray-200 text-gray-800' },
  fog: { label: 'Névoa', color: 'bg-gray-300 text-gray-800' },
  light_drizzle: { label: 'Garoa leve', color: 'bg-blue-100 text-blue-800' },
  moderate_drizzle: { label: 'Garoa moderada', color: 'bg-blue-200 text-blue-800' },
  dense_drizzle: { label: 'Garoa intensa', color: 'bg-blue-300 text-blue-800' },
  light_rain: { label: 'Chuva leve', color: 'bg-blue-200 text-blue-800' },
  moderate_rain: { label: 'Chuva moderada', color: 'bg-blue-300 text-blue-800' },
  heavy_rain: { label: 'Chuva forte', color: 'bg-blue-400 text-blue-900' },
  light_snow: { label: 'Neve leve', color: 'bg-cyan-100 text-cyan-800' },
  moderate_snow: { label: 'Neve moderada', color: 'bg-cyan-200 text-cyan-800' },
  heavy_snow: { label: 'Neve forte', color: 'bg-cyan-300 text-cyan-800' },
  light_showers: { label: 'Pancadas leves', color: 'bg-blue-200 text-blue-800' },
  moderate_showers: { label: 'Pancadas moderadas', color: 'bg-blue-300 text-blue-800' },
  heavy_showers: { label: 'Pancadas fortes', color: 'bg-blue-400 text-blue-900' },
  thunderstorm: { label: 'Tempestade', color: 'bg-purple-200 text-purple-800' },
  thunderstorm_hail: { label: 'Tempestade com granizo', color: 'bg-purple-300 text-purple-900' },
}
