package entities

type WeatherModal struct {
	Latitude             float64 `json:"latitude"`
	Longitude            float64 `json:"longitude"`
	GenerationtimeMs     float64 `json:"generationtime_ms"`
	UtcOffsetSeconds     int     `json:"utc_offset_seconds"`
	Timezone             string  `json:"timezone"`
	TimezoneAbbreviation string  `json:"timezone_abbreviation"`
	Elevation            float64 `json:"elevation"`
	CurrentUnits         struct {
		Time                     string `json:"time"`
		Interval                 string `json:"interval"`
		Temperature2M            string `json:"temperature_2m"`
		RelativeHumidity2M       string `json:"relative_humidity_2m"`
		PrecipitationProbability string `json:"precipitation_probability"`
		Precipitation            string `json:"precipitation"`
		Rain                     string `json:"rain"`
		WeatherCode              string `json:"weather_code"`
		PressureMsl              string `json:"pressure_msl"`
		CloudCover               string `json:"cloud_cover"`
		Visibility               string `json:"visibility"`
		Evapotranspiration       string `json:"evapotranspiration"`
		Et0FaoEvapotranspiration string `json:"et0_fao_evapotranspiration"`
		WindSpeed10M             string `json:"wind_speed_10m"`
		WindSpeed80M             string `json:"wind_speed_80m"`
		WindSpeed120M            string `json:"wind_speed_120m"`
		WindDirection10M         string `json:"wind_direction_10m"`
		WindDirection80M         string `json:"wind_direction_80m"`
		WindDirection120M        string `json:"wind_direction_120m"`
		WindSpeed180M            string `json:"wind_speed_180m"`
		WindDirection180M        string `json:"wind_direction_180m"`
		WindGusts10M             string `json:"wind_gusts_10m"`
		Temperature80M           string `json:"temperature_80m"`
		Temperature120M          string `json:"temperature_120m"`
		Temperature180M          string `json:"temperature_180m"`
		IsDay                    string `json:"is_day"`
		UvIndex                  string `json:"uv_index"`
		UvIndexClearSky          string `json:"uv_index_clear_sky"`
		DirectRadiation          string `json:"direct_radiation"`
	} `json:"current_units"`
	Current struct {
		Time                     string  `json:"time"`
		Interval                 int     `json:"interval"`
		Temperature2M            float64 `json:"temperature_2m"`
		RelativeHumidity2M       int     `json:"relative_humidity_2m"`
		PrecipitationProbability int     `json:"precipitation_probability"`
		Precipitation            float64 `json:"precipitation"`
		Rain                     float64 `json:"rain"`
		WeatherCode              int     `json:"weather_code"`
		PressureMsl              float64 `json:"pressure_msl"`
		CloudCover               int     `json:"cloud_cover"`
		Visibility               float64 `json:"visibility"`
		Evapotranspiration       float64 `json:"evapotranspiration"`
		Et0FaoEvapotranspiration float64 `json:"et0_fao_evapotranspiration"`
		WindSpeed10M             float64 `json:"wind_speed_10m"`
		WindSpeed80M             float64 `json:"wind_speed_80m"`
		WindSpeed120M            float64 `json:"wind_speed_120m"`
		WindDirection10M         int     `json:"wind_direction_10m"`
		WindDirection80M         int     `json:"wind_direction_80m"`
		WindDirection120M        int     `json:"wind_direction_120m"`
		WindSpeed180M            float64 `json:"wind_speed_180m"`
		WindDirection180M        int     `json:"wind_direction_180m"`
		WindGusts10M             float64 `json:"wind_gusts_10m"`
		Temperature80M           float64 `json:"temperature_80m"`
		Temperature120M          float64 `json:"temperature_120m"`
		Temperature180M          float64 `json:"temperature_180m"`
		IsDay                    int     `json:"is_day"`
		UvIndex                  float64 `json:"uv_index"`
		UvIndexClearSky          float64 `json:"uv_index_clear_sky"`
		DirectRadiation          float64 `json:"direct_radiation"`
	} `json:"current"`
}
